name: subtitleenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - pip:
      - fastapi
      - uvicorn
      - python-multipart
      - openai-whisper
      - transformers
      - torch
      - jiwer
      - rouge-score
      - pandas
      - python-dotenv
      - pydantic
      - tqdm
      - sentencepiece
      - notebook
      - ipykernel
